import type { Metadata } from 'next'
import { Arimo } from 'next/font/google'
import './globals.css'

import MainContainer from '../../components/MainContainer/MainContainer'
import Footer from '../../components/Footer/Footer'
import Navbar from '../../components/Sidebar/Sidebar'

const inter = Arimo({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}
        <MainContainer>
         
        </MainContainer>
        <Footer></Footer>
      </body>
    </html>
  )
}
